FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project
COPY . .

# Copy entrypoint script
# COPY entrypoint.sh /entrypoint.sh

# Expose the port (if needed, Celery might not need this)
EXPOSE 8000

# Entrypoint
# ENTRYPOINT ["/entrypoint.sh"]

# Default command for Celery
CMD ["celery", "-A", "webScrapify", "worker", "--loglevel=info"]
